# Generated by Django 4.2.5 on 2023-09-15 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.CharField(default='', max_length=200)),
                ('desc', models.TextField(default='write!')),
            ],
            options={
                'db_table': 'StreetModel',
            },
        ),
    ]
